=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|backbone|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|backbone|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|Vivaldi|Cluster|Cluster_torus|Cluster_fat_tree) #REQUIRED>

<!ELEMENT storage_type ((model_prop|prop)*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">
<!ATTLIST storage_type content_type  CDATA "txt_unix">

<!ELEMENT mount EMPTY>
<!ATTLIST mount storageId CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">
<!ATTLIST host pstate CDATA "0.0">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">
<!ATTLIST storage content_type  CDATA "txt_unix">
<!ATTLIST storage attach CDATA #REQUIRED>

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster (prop*)>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster topology (FLAT|TORUS|FAT_TREE) "FLAT">
<!ATTLIST cluster topo_parameters CDATA "">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">
<!ATTLIST cluster limiter_link CDATA "">
<!ATTLIST cluster loopback_bw CDATA "">
<!ATTLIST cluster loopback_lat CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT backbone EMPTY>
<!ATTLIST backbone id CDATA #REQUIRED>
<!ATTLIST backbone bandwidth CDATA  #REQUIRED>
<!ATTLIST backbone latency CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT model_prop EMPTY>
<!ATTLIST model_prop id CDATA #REQUIRED> <!-- <!ATTLIST model_prop key CDATA #REQUIRED> -->
<!ATTLIST model_prop value CDATA #REQUIRED>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/java/masterslave/masterslaveDeployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="Jacquelin" function="masterslave.Master">
     <argument value="5"/>     <!-- Amount of tasks to dispatch -->
     <argument value="50000"/> <!-- Computation size of each task -->
     <argument value="10"/>    <!-- Communication size of each one -->
     <argument value="7"/>     <!-- Amount of slaves waiting for orders -->
  </process>
  
  <process host="Jackson" function="masterslave.Forwarder">
     <argument value="0"/>  <!-- Input mailbox -->
     <argument value="7"/>  <!-- First output mailbox -->
     <argument value="8"/>  <!-- Last output mailbox -->
  </process>
  <process host="Casavant" function="masterslave.Forwarder">
     <argument value="1"/>  <!-- Input mailbox -->
     <argument value="9"/>  <!-- First output mailbox -->
     <argument value="10"/> <!-- Last output mailbox -->
  </process>
  
  <process host="iRMX" function="masterslave.Slave">
     <argument value="2"/>  <!-- Input mailbox -->
  </process>
  <process host="Bousquet" function="masterslave.Slave">
     <argument value="3"/>  <!-- Input mailbox -->
  </process>  
  <process host="Soucy" function="masterslave.Slave">
     <argument value="4"/>  <!-- Input mailbox -->
  </process>  
  <process host="Kuenning" function="masterslave.Slave">
     <argument value="5"/>  <!-- Input mailbox -->
  </process>  
  <process host="Browne" function="masterslave.Slave">
     <argument value="6"/>  <!-- Input mailbox -->
  </process>  
  <process host="Stephen" function="masterslave.Slave">
     <argument value="7"/>  <!-- Input mailbox -->
  </process>  
  <process host="Robert" function="masterslave.Slave">
     <argument value="8"/>  <!-- Input mailbox -->
  </process>  
  <process host="Sirois" function="masterslave.Slave">
     <argument value="9"/>  <!-- Input mailbox -->
  </process>  
  <process host="Monique" function="masterslave.Slave">
     <argument value="10"/>  <!-- Input mailbox -->
  </process>  
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/platforms/cluster_and_one_host.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
 <AS id="AS0"  routing="Full">   
  <cluster id="my_cluster_1" prefix="c-" suffix=".me"
    	   radical="0-1" power="1Gf" bw="125MBps" lat="50us"
           router_id="router1"/>

  <AS id="AS1" routing="None">
    <host id="host1" power="1Gf"/>
  </AS>

  <link id="link1" bandwidth="100kBps" latency="10ms"/>
  
  <ASroute src="my_cluster_1" dst="AS1"
    gw_src="router1" gw_dst="host1">
    <link_ctn id="link1"/>
  </ASroute>
 </AS>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/platforms/conf/gridpp_grid_2004.xml
<!-- This platform was automatically converted from the OptorSim platform.

  As such, it only contains information of the cluster interconnexion,
  not on the caracteristics of each cluster. In a sense, it describes
  the network of a National Research and Education Network (NREN), but
  not of a computational platform.
  
  We hope that you find it useful anyway. I you know how to complete
  this information with data on the cluster configurations, please
  drop us a mail so that we can add this information. -->

<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
<AS  id="AS0"  routing="Floyd">
<!--0 WC_Gla-->
<!--1 WC_Edi-->
<!--2 WC_Manc-->
<!--3 WC_Leeds-->
<!--4 WC_Reading-->
<!--5 WC_London-->
<!--6 WC_Bristol-->
<!--7 WC_Portsmouth-->
<!--8 Gla_router-->
<!--9 Edi_router-->
<!--10 NorMAN-->
<!--11 YHMAN-->
<!--12 EastNet-->
<!--13 LMN-->
<!--14 SWAN_BWEMAN-->
<!--15 TVN-->
<!--16 MidMAN-->
<!--17 NNW_router-->
<!--18 Glasgow-->
<!--19 Edi-->
<!--20 Durham-->
<!--21 Sheffield-->
<!--22 Cam-->
<!--23 UCL-->
<!--24 IC-->
<!--25 QMW-->
<!--26 Brunel-->
<!--27 RHNBC-->
<!--28 Bristol-->
<!--29 RAL-->
<!--30 Oxford-->
<!--31 B_ham-->
<!--32 L_pool-->
<!--33 Manc-->
<!--34 Lanc-->
<!--35 CERN-->
	<host id="WC_Edi" power="1f"/>
	<host id="WC_Manc" power="1f"/>
	<host id="Gla_router" power="1f"/>
	<host id="Glasgow" power="20Mf"/>
	<host id="Edi" power="25.6Mf"/>
	<host id="Durham" power="4.134Mf"/>
	<host id="Sheffield" power="49.64Mf"/>
	<host id="Cam" power="1.32Mf"/>
	<host id="UCL" power="22.5Mf"/>
	<host id="IC" power="440Mf"/>
	<host id="QMW" power="44Mf"/>
	<host id="Brunel" power="85.68Mf"/>
	<host id="RHNBC" power="7.2Mf"/>
	<host id="Bristol" power="60Mf"/>
	<host id="RAL" power="556.956Mf"/>
	<host id="Oxford" power="156.56Mf"/>
	<host id="B_ham" power="13.5Mf"/>
	<host id="L_pool" power="308.07Mf"/>
	<host id="Manc" power="22.5Mf"/>
	<host id="Lanc" power="204.8Mf"/>
	<host id="CERN" power="1f"/>

	<router id="WC_Gla"/>
	<router id="WC_Leeds"/>
	<router id="WC_Reading"/>
	<router id="WC_London"/>
	<router id="WC_Bristol"/>
	<router id="WC_Portsmouth"/>
	<router id="Edi_router"/>
	<router id="NorMAN"/>
	<router id="YHMAN"/>
	<router id="EastNet"/>
	<router id="LMN"/>
	<router id="SWAN_BWEMAN"/>
	<router id="TVN"/>
	<router id="MidMAN"/>
	<router id="NNW_router"/>

	<link id="link0" bandwidth="10kBps"/>
	<link id="link1" bandwidth="10kBps"/>
	<link id="link2" bandwidth="1kBps"/>
	<link id="link3" bandwidth="10kBps"/>
	<link id="link4" bandwidth="1kBps"/>
	<link id="link5" bandwidth="10kBps"/>
	<link id="link6" bandwidth="10kBps"/>
	<link id="link7" bandwidth="1kBps"/>
	<link id="link8" bandwidth="1kBps"/>
	<link id="link9" bandwidth="10kBps"/>
	<link id="link10" bandwidth="622Bps"/>
	<link id="link11" bandwidth="1kBps"/>
	<link id="link12" bandwidth="10kBps"/>
	<link id="link13" bandwidth="10kBps"/>
	<link id="link14" bandwidth="622Bps"/>
	<link id="link15" bandwidth="10kBps"/>
	<link id="link16" bandwidth="1kBps"/>
	<link id="link17" bandwidth="1kBps"/>
	<link id="link18" bandwidth="10kBps"/>
	<link id="link19" bandwidth="622Bps"/>
	<link id="link20" bandwidth="2.5kBps"/>
	<link id="link21" bandwidth="1kBps"/>
	<link id="link22" bandwidth="1kBps"/>
	<link id="link23" bandwidth="155Bps"/>
	<link id="link24" bandwidth="155Bps"/>
	<link id="link25" bandwidth="155Bps"/>
	<link id="link26" bandwidth="155Bps"/>
	<link id="link27" bandwidth="155Bps"/>
	<link id="link28" bandwidth="155Bps"/>
	<link id="link29" bandwidth="155Bps"/>
	<link id="link30" bandwidth="155Bps"/>
	<link id="link31" bandwidth="622Bps"/>
	<link id="link32" bandwidth="622Bps"/>
	<link id="link33" bandwidth="622Bps"/>
	<link id="link34" bandwidth="622Bps"/>
	<link id="link35" bandwidth="155Bps"/>
	<link id="link36" bandwidth="1kBps"/>
	<link id="link37" bandwidth="155Bps"/>

	<route src="WC_Gla" dst="WC_Gla">
		<link_ctn id="link0"/>
	</route>
	<route src="WC_Gla" dst="WC_Edi">
		<link_ctn id="link1"/>
	</route>
	<route src="WC_Gla" dst="WC_Portsmouth">
		<link_ctn id="link2"/>
	</route>
	<route src="WC_Edi" dst="WC_Manc">
		<link_ctn id="link3"/>
	</route>
	<route src="WC_Edi" dst="Gla_router">
		<link_ctn id="link4"/>
	</route>
	<route src="WC_Manc" dst="WC_Manc">
		<link_ctn id="link5"/>
	</route>
	<route src="WC_Manc" dst="WC_Leeds">
		<link_ctn id="link6"/>
	</route>
	<route src="WC_Manc" dst="TVN">
		<link_ctn id="link7"/>
	</route>
	<route src="WC_Manc" dst="MidMAN">
		<link_ctn id="link8"/>
	</route>
	<route src="WC_Leeds" dst="WC_Reading">
		<link_ctn id="link9"/>
	</route>
	<route src="WC_Leeds" dst="Edi_router">
		<link_ctn id="link10"/>
	</route>
	<route src="WC_Leeds" dst="NorMAN">
		<link_ctn id="link11"/>
	</route>
	<route src="WC_Reading" dst="WC_Reading">
		<link_ctn id="link12"/>
	</route>
	<route src="WC_Reading" dst="WC_London">
		<link_ctn id="link13"/>
	</route>
	<route src="WC_Reading" dst="SWAN_BWEMAN">
		<link_ctn id="link14"/>
	</route>
	<route src="WC_London" dst="WC_Bristol">
		<link_ctn id="link15"/>
	</route>
	<route src="WC_London" dst="YHMAN">
		<link_ctn id="link16"/>
	</route>
	<route src="WC_London" dst="EastNet">
		<link_ctn id="link17"/>
	</route>
	<route src="WC_Bristol" dst="WC_Bristol">
		<link_ctn id="link18"/>
	</route>
	<route src="WC_Bristol" dst="LMN">
		<link_ctn id="link19"/>
	</route>
	<route src="WC_Portsmouth" dst="Lanc">
		<link_ctn id="link20"/>
	</route>
	<route src="Gla_router" dst="NNW_router">
		<link_ctn id="link21"/>
	</route>
	<route src="Edi_router" dst="Glasgow">
		<link_ctn id="link22"/>
	</route>
	<route src="NorMAN" dst="Edi">
		<link_ctn id="link23"/>
	</route>
	<route src="YHMAN" dst="Durham">
		<link_ctn id="link24"/>
	</route>
	<route src="EastNet" dst="Sheffield">
		<link_ctn id="link25"/>
	</route>
	<route src="LMN" dst="Cam">
		<link_ctn id="link26"/>
	</route>
	<route src="LMN" dst="UCL">
		<link_ctn id="link27"/>
	</route>
	<route src="LMN" dst="IC">
		<link_ctn id="link28"/>
	</route>
	<route src="LMN" dst="QMW">
		<link_ctn id="link29"/>
	</route>
	<route src="LMN" dst="Brunel">
		<link_ctn id="link30"/>
	</route>
	<route src="SWAN_BWEMAN" dst="RHNBC">
		<link_ctn id="link31"/>
	</route>
	<route src="TVN" dst="Bristol">
		<link_ctn id="link32"/>
	</route>
	<route src="TVN" dst="RAL">
		<link_ctn id="link33"/>
	</route>
	<route src="MidMAN" dst="Oxford">
		<link_ctn id="link34"/>
	</route>
	<route src="NNW_router" dst="B_ham">
		<link_ctn id="link35"/>
	</route>
	<route src="NNW_router" dst="L_pool">
		<link_ctn id="link36"/>
	</route>
	<route src="NNW_router" dst="Manc">
		<link_ctn id="link37"/>
	</route>
</AS>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/gtnets/dogbone-p.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3"> 
 <AS  id="AS0"  routing="Full">
 <!---  dogbone
 -->
 
 
   <host id="S1" power="1Gf"/>
   <host id="C1" power="1Gf"/>
   <host id="S2" power="1Gf"/>
   <host id="C2" power="1Gf"/>
   <router id="R1"/>
   <router id="R2"/>
 
   <link id="1" bandwidth="100MBps" latency="10ms"/>
   <link id="2" bandwidth="100MBps" latency="10ms"/>
   <link id="3" bandwidth="100MBps" latency="10ms"/>
   <link id="4" bandwidth="100MBps" latency="10ms"/>
   <link id="5" bandwidth="100MBps" latency="10ms"/>
 
 
   <route src="S1" dst="C1">
      <link_ctn id="1"/>
      <link_ctn id="2"/>
      <link_ctn id="3"/>
   </route>
 
   <route src="S2" dst="C2">
      <link_ctn id="4"/>
      <link_ctn id="2"/>
      <link_ctn id="5"/>
   </route>
 
   <route src="S1" dst="C2">
      <link_ctn id="1"/>
      <link_ctn id="2"/>
      <link_ctn id="5"/>
   </route>
 
   <route src="S2" dst="C1">
      <link_ctn id="4"/>
      <link_ctn id="2"/>
      <link_ctn id="3"/>
   </route>
 
   <route src="S1" dst="R1">
      <link_ctn id="1"/>
   </route>
 
   <route src="R1" dst="R2">
      <link_ctn id="2"/>
   </route>
 
   <route src="R2" dst="C1">
      <link_ctn id="3"/>
   </route>
 
   <route src="S2" dst="R1">
      <link_ctn id="4"/>
   </route>
 
   <route src="R2" dst="C2">
      <link_ctn id="5"/>
   </route>
 </AS>
 </platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/kademlia/kademlia.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">

  <process host="Jacquelin" function="node">
    <argument value="0x0000"/>          <!-- my id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>

  <process host="Boivin" function="node">
    <argument value="0x0001"/>          <!-- my id -->
    <argument value="0"/>               <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>

  <process host="Jean_Yves" function="node">
    <argument value="0x0003"/>          <!-- my id -->
    <argument value="0x0001"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>

  <process host="TeX" function="node">
    <argument value="0x0007"/>          <!-- my id -->
    <argument value="0x0003"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="Geoff" function="node">
    <argument value="0x000f"/>          <!-- my id -->
    <argument value="0x0007"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="Disney" function="node">
    <argument value="0x001f"/>          <!-- my id -->
    <argument value="0x000f"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="iRMX" function="node">
    <argument value="0x003f"/>          <!-- my id -->
    <argument value="0x001f"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="McGee" function="node">
    <argument value="0x007f"/>          <!-- my id -->
    <argument value="0x003f"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="Gatien" function="node">
    <argument value="0x00ff"/>          <!-- my id -->
    <argument value="0x007f"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="Laroche" function="node">
    <argument value="0x01ff"/>          <!-- my id -->
    <argument value="0x00ff"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
  <process host="Tanguay" function="node">
    <argument value="0x03ff"/>          <!-- my id -->
    <argument value="0x01ff"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
   <process host="Morin" function="node">
    <argument value="0x07ff"/>          <!-- my id -->
    <argument value="0x03ff"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
   <process host="Ethernet" function="node">
    <argument value="0x0fff"/>          <!-- my id -->
    <argument value="0x0000"/>          <!-- known id -->
    <argument value ="900"/>            <!-- deadline -->
  </process>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/masterslave/deployment_masterslave.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <!-- The master process (with some arguments) -->
  <process host="Tremblay" function="master">
     <argument value="20"/>       <!-- Number of tasks -->
     <argument value="50000000"/>  <!-- Computation size of tasks -->
     <argument value="1000000"/>   <!-- Communication size of tasks -->
     <argument value="Jupiter"/>  <!-- First slave -->
     <argument value="Fafard"/>   <!-- Second slave -->
     <argument value="Ginette"/>  <!-- Third slave -->
     <argument value="Bourassa"/> <!-- Last slave -->
     <argument value="Tremblay"/> <!-- Me! I can work too! -->
  </process>
  <!-- The slave process (with no argument) -->
  <process host="Tremblay" function="slave" on_failure="RESTART"/>
  <process host="Jupiter" function="slave" on_failure="RESTART"/>
  <process host="Fafard" function="slave" on_failure="RESTART"/>
  <process host="Ginette" function="slave" on_failure="RESTART"/>
  <process host="Bourassa" function="slave" on_failure="RESTART"/>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/pastry/pastry10.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="c-0.me" function="node"><argument value="42"/><argument value="6000000"/></process>
  <process host="c-1.me" function="node"><argument value="366680" /><argument value="42" /><argument value="10" /><argument value="6000000" /></process>
  <process host="c-2.me" function="node"><argument value="533744" /><argument value="366680" /><argument value="20" /><argument value="6000000" /></process>
  <process host="c-3.me" function="node"><argument value="1319738" /><argument value="42" /><argument value="30" /><argument value="6000000" /></process>
  <process host="c-4.me" function="node"><argument value="16509405" /><argument value="366680" /><argument value="40" /><argument value="6000000" /></process>
  <process host="c-5.me" function="node"><argument value="10874876" /><argument value="533744" /><argument value="50" /><argument value="6000000" /></process>
  <process host="c-6.me" function="node"><argument value="16728096" /><argument value="1319738" /><argument value="60" /><argument value="6000000" /></process>
  <process host="c-7.me" function="node"><argument value="10004760" /><argument value="16509405" /><argument value="70" /><argument value="6000000" /></process>
  <process host="c-8.me" function="node"><argument value="6518808" /><argument value="42" /><argument value="80" /><argument value="6000000" /></process>
  <process host="c-9.me" function="node"><argument value="2015253" /><argument value="1319738" /><argument value="90" /><argument value="6000000" /></process>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/platforms/deployment_remote_io.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="alice" function="host">
    <argument value = "c:\Windows\setupact.log"/>
  </process>
  <process host="bob" function="host">
    <argument value = "/scratch/lib/libsimgrid.so.3.6.2"/>
    <argument value = "/scratch/doc/simgrid/examples/platforms/g5k.xml"/>
    <argument value = "alice"/>
    <argument value = "c:\Windows\Platforms\g5k.xml"/>
    <argument value = "0"/>
  </process>
  <process host="carl" function="host">
    <argument value = "/scratch/lib/libsimgrid.so.3.6.2"/>
  </process>
  <process host="dave" function="host">
    <argument value = "c:\Windows\bootstat.dat"/>
    <argument value = "c:\Windows\Professional.xml"/>
    <argument value = "carl"/>
    <argument value = "/scratch/mailbox/Professional.xml"/>
    <argument value = "1"/>
  </process>
</platform>
