=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|backbone|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|backbone|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|Vivaldi|Cluster|Cluster_torus|Cluster_fat_tree) #REQUIRED>

<!ELEMENT storage_type ((model_prop|prop)*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">
<!ATTLIST storage_type content_type  CDATA "txt_unix">

<!ELEMENT mount EMPTY>
<!ATTLIST mount storageId CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">
<!ATTLIST host pstate CDATA "0.0">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">
<!ATTLIST storage content_type  CDATA "txt_unix">
<!ATTLIST storage attach CDATA #REQUIRED>

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster (prop*)>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster topology (FLAT|TORUS|FAT_TREE) "FLAT">
<!ATTLIST cluster topo_parameters CDATA "">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">
<!ATTLIST cluster limiter_link CDATA "">
<!ATTLIST cluster loopback_bw CDATA "">
<!ATTLIST cluster loopback_lat CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT backbone EMPTY>
<!ATTLIST backbone id CDATA #REQUIRED>
<!ATTLIST backbone bandwidth CDATA  #REQUIRED>
<!ATTLIST backbone latency CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT model_prop EMPTY>
<!ATTLIST model_prop id CDATA #REQUIRED> <!-- <!ATTLIST model_prop key CDATA #REQUIRED> -->
<!ATTLIST model_prop value CDATA #REQUIRED>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/teshsuite/simdag/platforms/route_override.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <cluster id="bob_cluster" prefix="bob" suffix=".hamburger.edu"
 	   radical="0-4" power="1Gf" bw="125MBps" lat="50us"
 	   bb_bw="2.25GBps" bb_lat="500us"/>
 
   <cluster id="alice_cluster" prefix="alice" suffix=".crepe.fr"
 	   radical="0-4" power="1Gf" bw="125MBps" lat="50us"
 	   bb_bw="2.25GBps" bb_lat="500us"/>
 
   <link id="backbone" bandwidth="1.25GBps" latency="500us"/>
 
   <route:multi src="bob_cluster" dst="alice_cluster" symmetric="YES">
     <link_ctn id="backbone"/>
     <link_ctn id="$dst"/>
   </route:multi>
 
   <route:multi src="bob0.hamburger.edu" dst="$*" action="OVERRIDE" symmetric="NO">
     <link_ctn id="$src"/>
     <link_ctn id="backbone"/>
     <link_ctn id="$dst"/>
   </route:multi>
 
   <route:multi src="bob0.hamburger.edu" dst="bob_cluster" action="OVERRIDE" symmetric="NO">
     <link_ctn id="$src"/>
     <link_ctn id="bob_cluster_bb"/>
     <link_ctn id="$dst"/>
   </route:multi>
 
 </AS>
 </platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/teshsuite/msg/trace/test-hbp1.0-hbp3.0-hbp4.0.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="Cpu B" function="test_trace" start_time="10">
  	<argument value="25"/>
  	<argument value="1.0"/>
  </process>
  <process host="Cpu B" function="test_trace" start_time="10">
  	<argument value="75"/>
  	<argument value="3.0"/>
  </process>
  <process host="Cpu B" function="test_trace" start_time="20">
  	<argument value="120"/>
  	<argument value="4.0"/>
  </process>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/masterslave/deployment_masterslave_forwarder.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="Jacquelin" function="master">
     <argument value="20"/>       <!-- Number of tasks -->
     <argument value="5000000"/>  <!-- Computation size of tasks -->
     <argument value="100000"/>   <!-- Communication size of tasks -->
     <argument value="iRMX"/>     <!-- First slave -->
     <argument value="Casavant"/> <!-- Second slave -->
     <argument value="Bousquet"/> <!-- Third slave -->
     <argument value="Soucy"/>    <!-- Fourth slave -->
     <argument value="Jackson"/>  <!-- Last slave -->
  </process>
  <process host="Jackson" function="forwarder">
     <argument value="Kuenning"/>
     <argument value="Browne"/> 
     <argument value="Stephen"/>
 </process>
  <process host="Casavant" function="forwarder">
     <argument value="Robert"/>
     <argument value="Sirois"/> 
     <argument value="Monique"/>
 </process>
  <process host="iRMX" function="slave"/>
  <process host="Bousquet" function="slave"/>
  <process host="Soucy" function="slave"/>
  <process host="Kuenning" function="slave"/>
  <process host="Browne" function="slave"/>
  <process host="Stephen" function="slave"/>
  <process host="Robert" function="slave"/>
  <process host="Sirois" function="slave"/>
  <process host="Monique" function="slave"/>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/chainsend/deployment_tesh.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3"><!-- For using with chainsend -->

  <!-- Broadcaster -->
  <process host="Jacquelin" function="broadcaster">
	<argument value="8"/> <!-- number of peers -->
	<argument value="256"/> <!-- number of pieces -->
  </process>

  <!-- Peers -->
  <process host="Boivin" function="peer">
  	<argument value="1"/>
  </process>
  <process host="Jean_Yves" function="peer">
  	<argument value="2"/>
  </process>
  <process host="TeX" function="peer">
  	<argument value="3"/>
  </process>
  <process host="Geoff" function="peer">
  	<argument value="4"/>
  </process>
  <process host="Disney" function="peer">
  	<argument value="5"/>
  </process>
  <process host="iRMX" function="peer">
  	<argument value="6"/>
  </process>
  <process host="McGee" function="peer">
  	<argument value="7"/>
  </process>
  <process host="Gatien" function="peer">
  	<argument value="8"/>
  </process>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/platforms/prop.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 
 <!-- This file describe a super simple platform which main interest is
      to define some properties on hosts, processes and links. 
      It is used in several regression cases on properties -->
 
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <prop id="filename" value="prop.xml"/>
   <prop id="date" value="31-08-12"/>
   <prop id="author" value="pnavarro"/>
   
   <AS  id="AS3"  routing="Full">
	   <AS id="AS1" routing="None">
	       <prop id="name" value="AS1"/>
	   </AS>
	   
	   <AS id="AS2" routing="None">
	       <prop id="name" value="AS2"/>
	   </AS>
   </AS>
   
   <AS  id="AS4"  routing="Full">
	   <host id="host1" power="1Gf">
	     <prop id="Hdd" value="180"/>
	     <prop id="mem" value="4"/>
	   </host>
	   
	   <host id="host2" power="1Gf">
	     <prop id="Hdd" value="120"/>
	   </host>
	   
	   <link id="l1" bandwidth="125MBps" latency="100us">
	     <prop id="type" value="Ethernet"/>
	   </link>
	   
	   <link id="l2" bandwidth="125MBps" latency="100us">
	     <prop id="type" value="ethernet"/>
	   </link>
	   <route src="host1" dst="host2"><link_ctn id="l1"/><link_ctn id="l2"/></route>
   </AS>
 </AS>
 </platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/platforms/small_platform_with_failures.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <!-- ljlkj -->
   <host id="Tremblay" power="25Mf"/>
   <host id="Jupiter" power="25Mf" state_file="jupiter_state.trace"/>
   <host id="Fafard" power="25Mf" state_file="fafard_state.trace" />
   <host id="Ginette" power="25Mf" state_file="ginette_state.trace"/>
   <host id="Bourassa" power="25Mf"state_file="bourassa_state.trace"/>
   <link id="1" bandwidth="1MBps" latency="0"/>
   <link id="2" bandwidth="1MBps" latency="0"/>
   <link id="3" bandwidth="1MBps" latency="0" state_file="link3_state.trace" />
   <link id="4" bandwidth="1MBps" latency="0" state_file="link4_state.trace" />
   <link id="5" bandwidth="1MBps" latency="0"/>
   <link id="6" bandwidth="1MBps" latency="0"/>
   <link id="7" bandwidth="1MBps" latency="0"/>
   <link id="8" bandwidth="1MBps" latency="0"/>
   <link id="9" bandwidth="1MBps" latency="0"/>
   <link id="10" bandwidth="1MBps" latency="0"/>
   <link id="loopback_FATPIPE" bandwidth="10MBps" latency="0" sharing_policy="FATPIPE"/>
   <link id="loopback" bandwidth="100MBps" latency="0"/>
   <route src="Tremblay" dst="Tremblay"><link_ctn id="loopback"/></route>
   <route src="Jupiter" dst="Jupiter"><link_ctn id="loopback"/></route>
   <route src="Fafard" dst="Fafard"><link_ctn id="loopback"/></route>
   <route src="Ginette" dst="Ginette"><link_ctn id="loopback"/></route>
   <route src="Bourassa" dst="Bourassa"><link_ctn id="loopback"/></route>
   <route src="Tremblay" dst="Jupiter">
     <link_ctn id="1"/>
   </route>
   <route src="Tremblay" dst="Fafard">
     <link_ctn id="2"/>
   </route>
   <route src="Tremblay" dst="Ginette">
     <link_ctn id="3"/>
   </route>
   <route src="Tremblay" dst="Bourassa">
     <link_ctn id="4"/>
   </route>
   <route src="Jupiter" dst="Fafard">
     <link_ctn id="5"/>
   </route>
   <route src="Jupiter" dst="Ginette">
     <link_ctn id="6"/>
   </route>
   <route src="Jupiter" dst="Bourassa">
     <link_ctn id="7"/>
   </route>
   <route src="Fafard" dst="Ginette">
     <link_ctn id="8"/>
   </route>
   <route src="Fafard" dst="Bourassa">
     <link_ctn id="9"/>
   </route>
   <route src="Ginette" dst="Bourassa">
     <link_ctn id="10"/>
   </route>
 </AS>
 </platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/tracing/deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <!-- The master process (with some arguments) -->
  <process host="Tremblay" function="master">
     <argument value="20"/>       <!-- Number of tasks -->
     <argument value="50000000"/>  <!-- Computation size of tasks -->
     <argument value="1000000"/>   <!-- Communication size of tasks -->
     <argument value="5"/>         <!-- Number of slaves -->
  </process>
  <!-- The slave processes (with mailbox to listen on as argument) -->
  <process host="Tremblay" function="slave"/>
  <process host="Jupiter" function="slave"/>
  <process host="Fafard" function="slave"/>
  <process host="Ginette" function="slave"/>
  <process host="Bourassa" function="slave"/>

</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/msg/mc/platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="HostA" power="137.333Mf"/>
   <host id="HostB" power="98.095Mf"/>
   <host id="HostC" power="98.095Mf"/>
   <host id="HostD" power="98.095Mf"/>
   <link id="1" bandwidth="3.430125MBps" latency="536.941us"/>
   <link id="2" bandwidth="3.430125MBps" latency="536.941us"/>
   <link id="3" bandwidth="3.430125MBps" latency="536.941us"/>
   <route src="HostA" dst="HostB"><link_ctn id="1"/></route>
   <route src="HostA" dst="HostC"><link_ctn id="2"/></route>
   <route src="HostA" dst="HostD"><link_ctn id="3"/></route>
 </AS>
 </platform>
