=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((config|random)*,(include|cluster|cabinet|peer|AS|trace|trace_connect)*,(process)*)>
<!ATTLIST platform version CDATA "0.0">

<!ELEMENT include (include|cluster|cabinet|peer|AS|trace|trace_connect)*>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random EMPTY>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random seed CDATA "2147483647">
<!ATTLIST random radical CDATA "">
<!ATTLIST random generator (DRAND48|RAND|RNGSTREAM|NONE) "DRAND48">

<!ELEMENT trace_connect EMPTY>
<!ATTLIST trace_connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace_connect trace CDATA #REQUIRED>
<!ATTLIST trace_connect element CDATA #REQUIRED>

<!ELEMENT AS ((prop*),(((AS|include|storage_type|storage|link|backbone|cabinet|cluster|peer|trace|trace_connect)*,(ASroute|trace|trace_connect|bypassASroute)*,(trace|trace_connect)*)|((include|storage_type|storage|host|gpu|cabinet|router|link|backbone|trace|trace_connect|host_link)*,(route|trace|trace_connect|bypassRoute)*)))>
<!ATTLIST AS id CDATA #REQUIRED>
<!ATTLIST AS routing (Full|Floyd|Dijkstra|DijkstraCache|None|Vivaldi|Cluster|Cluster_torus|Cluster_fat_tree) #REQUIRED>

<!ELEMENT storage_type ((model_prop|prop)*)>
<!ATTLIST storage_type id       CDATA #REQUIRED>
<!ATTLIST storage_type model    CDATA #REQUIRED>
<!ATTLIST storage_type size     CDATA #REQUIRED>
<!ATTLIST storage_type content  CDATA "">
<!ATTLIST storage_type content_type  CDATA "txt_unix">

<!ELEMENT mount EMPTY>
<!ATTLIST mount storageId CDATA #REQUIRED>
<!ATTLIST mount name CDATA #REQUIRED>

<!ELEMENT mstorage EMPTY>
<!ATTLIST mstorage typeId CDATA #REQUIRED>
<!ATTLIST mstorage name CDATA #REQUIRED>

<!ELEMENT host (prop|mount|mstorage)*>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host core  CDATA "1">
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host coordinates  CDATA "">
<!ATTLIST host pstate CDATA "0.0">

<!ELEMENT storage (prop*)>
<!ATTLIST storage id CDATA #REQUIRED>
<!ATTLIST storage typeId CDATA #REQUIRED>
<!ATTLIST storage content  CDATA "">
<!ATTLIST storage content_type  CDATA "txt_unix">
<!ATTLIST storage attach CDATA #REQUIRED>

<!ELEMENT gpu EMPTY>
<!ATTLIST gpu name CDATA #REQUIRED>

<!ELEMENT host_link EMPTY>
<!ATTLIST host_link id CDATA #REQUIRED>
<!ATTLIST host_link up CDATA #REQUIRED>
<!ATTLIST host_link down CDATA #REQUIRED>

<!ELEMENT cluster (prop*)>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster core CDATA "1">
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster sharing_policy (SHARED|FULLDUPLEX|FATPIPE) "FULLDUPLEX">
<!ATTLIST cluster topology (FLAT|TORUS|FAT_TREE) "FLAT">
<!ATTLIST cluster topo_parameters CDATA "">
<!ATTLIST cluster bb_bw CDATA "">
<!ATTLIST cluster bb_lat CDATA "">
<!ATTLIST cluster bb_sharing_policy (SHARED|FATPIPE) "SHARED">
<!ATTLIST cluster availability_file CDATA "">
<!ATTLIST cluster state_file CDATA "">
<!ATTLIST cluster router_id CDATA "">
<!ATTLIST cluster limiter_link CDATA "">
<!ATTLIST cluster loopback_bw CDATA "">
<!ATTLIST cluster loopback_lat CDATA "">

<!ELEMENT cabinet EMPTY>
<!ATTLIST cabinet id CDATA #REQUIRED>
<!ATTLIST cabinet prefix CDATA #REQUIRED>
<!ATTLIST cabinet suffix CDATA #REQUIRED>
<!ATTLIST cabinet radical CDATA #REQUIRED>
<!ATTLIST cabinet power CDATA #REQUIRED>
<!ATTLIST cabinet bw CDATA #REQUIRED>
<!ATTLIST cabinet lat CDATA #REQUIRED>

<!ELEMENT peer EMPTY>
<!ATTLIST peer id CDATA #REQUIRED>
<!ATTLIST peer power CDATA #REQUIRED>
<!ATTLIST peer bw_in CDATA #REQUIRED>
<!ATTLIST peer bw_out CDATA #REQUIRED>
<!ATTLIST peer lat CDATA #REQUIRED>
<!ATTLIST peer coordinates CDATA "">
<!ATTLIST peer availability_file CDATA "">
<!ATTLIST peer state_file CDATA "">

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>
<!ATTLIST router coordinates  CDATA "">

<!ELEMENT backbone EMPTY>
<!ATTLIST backbone id CDATA #REQUIRED>
<!ATTLIST backbone bandwidth CDATA  #REQUIRED>
<!ATTLIST backbone latency CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE|FULLDUPLEX) "SHARED">

<!ELEMENT route (link_ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route symmetrical (YES|NO) "YES">

<!ELEMENT ASroute (link_ctn*)>
<!ATTLIST ASroute src CDATA #REQUIRED>
<!ATTLIST ASroute dst CDATA #REQUIRED>
<!ATTLIST ASroute gw_src CDATA #REQUIRED>
<!ATTLIST ASroute gw_dst CDATA #REQUIRED>
<!ATTLIST ASroute symmetrical (YES|NO) "YES">

<!ELEMENT link_ctn EMPTY>
<!ATTLIST link_ctn id CDATA #REQUIRED>
<!ATTLIST link_ctn direction (UP|DOWN|NONE) "NONE">

<!ELEMENT bypassRoute (link_ctn*)>
<!ATTLIST bypassRoute src CDATA #REQUIRED>
<!ATTLIST bypassRoute dst CDATA #REQUIRED>

<!ELEMENT bypassASroute (link_ctn*)>
<!ATTLIST bypassASroute src CDATA #REQUIRED>
<!ATTLIST bypassASroute dst CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_src CDATA #REQUIRED>
<!ATTLIST bypassASroute gw_dst CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">
<!ATTLIST process on_failure (DIE|RESTART) "DIE">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

<!ELEMENT config (prop*)>
<!ATTLIST config id CDATA "">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED> <!-- <!ATTLIST prop key CDATA #REQUIRED> -->
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT model_prop EMPTY>
<!ATTLIST model_prop id CDATA #REQUIRED> <!-- <!ATTLIST model_prop key CDATA #REQUIRED> -->
<!ATTLIST model_prop value CDATA #REQUIRED>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/teshsuite/simdag/platforms/bogus_two_hosts_asymetric-2.xml
<!-- THIS FILE IS INVALID.

It declares a route alice->bob and another bob->alice, both being different.
It is used to check that this (bogus) file is detected as is (see
two_hosts_asymetric.tesh) -->

<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="bob" power="1Gf"/>
   <host id="alice" power="500Mf"/>
 
   <link id="link1" bandwidth="125MBps" latency="50us"/>
   <link id="link2" bandwidth="125MBps" latency="50us"/>
   <link id="link3" bandwidth="125MBps" latency="50us"/>
   <link id="link4" bandwidth="125MBps" latency="50us"/>
   
   <route src="bob" dst="alice">
     <link_ctn id="link1"/><link_ctn id="link2"/><link_ctn id="link4"/>
   </route>

   <route src="alice" dst="bob">
     <link_ctn id="link4"/><link_ctn id="link3"/><link_ctn id="link1"/>
   </route>

 </AS>
 </platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/examples/simdag/two_hosts.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
   <AS  id="AS0"  routing="Full">
     <host id="Tremblay" power="25Mf"/>
     <host id="Jupiter" power="25Mf" 
           availability_file="jupiter_power.trace"/>

     <link id="1" bandwidth="125MBps" latency="100us" 
           bandwidth_file="link1_avail.trace"/>
     
     <route src="Tremblay" dst="Jupiter">
       <link_ctn id="1"/>
     </route>
   </AS>

   <trace id="Tremblay_power" periodicity="6.0">
     1.0 0.5
     4.0 1.0
   </trace>

   <trace_connect trace="Tremblay_power" element="Tremblay" kind="POWER"/>
</platform>

=== smallcat9603/simgrid/simgrid-template/MpiEnv/simgrid/Simgrid-git/teshsuite/simdag/platforms/three_hosts_non_symmetric_route.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
 <platform version="3">
 <AS  id="AS0"  routing="Full">
   <host id="bob" power="1Gf"/>
   <host id="alice" power="500Mf"/>
   <host id="trudy" power="250Mf"/>
 
   <link id="link1" bandwidth="125MBps" latency="50us"/>
   <link id="link2" bandwidth="125MBps" latency="50us"/>
   <link id="link3" bandwidth="125MBps" latency="50us"/>
 
   <route src="bob" dst="alice" symmetrical="NO">
     <link_ctn id="link1"/>
   </route>
   <route src="alice" dst="bob" symmetrical="NO">
     <link_ctn id="link2"/>
     <link_ctn id="link3"/>
   </route>
 
   <route src="bob" dst="trudy">
     <link_ctn id="link2"/>
   </route>
 
   <route src="trudy" dst="alice">
     <link_ctn id="link3"/>
   </route>
 </AS>
 </platform>
